[features]
resolution = true
skip-lint = false

[programs.localnet]
memo = "ETV8B7LGMaZYMRwWYimjKpwcoE1AQHNfFwMDynstK4wR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
